apiVersion: apps/v1
kind: Deployment
metadata:
  name: intelligent-tutoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: intelligent-tutoring
  template:
    metadata:
      labels:
        app: intelligent-tutoring
    spec:
      containers:
      - name: app
        image: intelligent-tutoring:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: intelligent-tutoring
spec:
  selector:
    app: intelligent-tutoring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
